theme: jekyll-theme-slate
title: Mohammad Mahdavi
description: Professor at Gisma University of Applied Sciences | Data Scientist | AI Specialist



plugins:
  - jekyll-scholar

scholar:
  bibliography: ["_includes/sections/references.bib"]
  style: apa